<?
header('Content-type: application/javascript');
include ("../_includes/settings.php");
include ("../_includes/function.database.php");
include ("../_includes/function.genpass.php");

echo "var windowsize = $(window).width();";
echo "\n";
echo "$(window).resize(function() {";
echo "\n";
	echo "var windowsize = $(window).width();";
	echo "\n";
echo "});";
echo "\n";
echo "if (windowsize <= 480) {";
echo "\n";
	echo "iTile1x1Width		=	12;";
	echo "\n";
	echo "iTile1x1Height	=	12;";
	echo "\n";
	echo "\n";
	echo "iTile1x2Width		=	12;";
	echo "\n";
	echo "iTile1x2Height	=	24;";
	echo "\n";
	echo "\n";
	echo "iTile2x1Width		=	12;";
	echo "\n";
	echo "iTile2x1Height	=	6;";
	echo "\n";
	echo "\n";
	echo "iTile2x2Width		=	12;";
	echo "\n";
	echo "iTile2x2Height	=	12;";
	echo "\n";
	echo "\n";
	echo "iTile2x3Width		=	12;";
	echo "\n";
	echo "iTile2x3Height	=	18;";
	echo "\n";
	echo "\n";
	echo "iTile3x2Width		=	12;";
	echo "\n";
	echo "iTile3x2Height	=	8;";
	echo "\n";
	echo "\n";
	echo "iTile2x4Width		=	12;";
	echo "\n";
	echo "iTile2x4Height	=	24;";
	echo "\n";
	echo "\n";
	echo "iTile4x2Width		=	12;";
	echo "\n";
	echo "iTile4x2Height	=	6;";
	echo "\n";
echo "} else {";
echo "\n";
	echo "iTile1x1Width		=	6;";
	echo "\n";
	echo "iTile1x1Height	=	6;";
	echo "\n";
	echo "\n";
	echo "iTile1x2Width		=	3;";
	echo "\n";
	echo "iTile1x2Height	=	6;";
	echo "\n";
	echo "\n";
	echo "iTile2x1Width		=	12;";
	echo "\n";
	echo "iTile2x1Height	=	6;";
	echo "\n";
	echo "\n";
	echo "iTile2x2Width		=	6;";
	echo "\n";
	echo "iTile2x2Height	=	6;";
	echo "\n";
	echo "\n";
	echo "iTile2x3Width		=	3;";
	echo "\n";
	echo "iTile2x3Height	=	6;";
	echo "\n";
	echo "\n";
	echo "iTile3x2Width		=	9;";
	echo "\n";
	echo "iTile3x2Height	=	6;";
	echo "\n";
	echo "\n";
	echo "iTile2x4Width		=	6;";
	echo "\n";
	echo "iTile2x4Height	=	6;";
	echo "\n";
	echo "\n";
	echo "iTile4x2Width		=	12;";
	echo "\n";
	echo "iTile4x2Height	=	6;";
	
//	echo "iTile1x1Width		=	1;";
//	echo "\n";
//	echo "iTile1x1Height	=	1;";
//	echo "\n";
//	echo "\n";
//	echo "iTile1x2Width		=	1;";
//	echo "\n";
//	echo "iTile1x2Height	=	2;";
//	echo "\n";
//	echo "\n";
//	echo "iTile2x1Width		=	2;";
//	echo "\n";
//	echo "iTile2x1Height	=	1;";
//	echo "\n";
//	echo "\n";
//	echo "iTile2x2Width		=	2;";
//	echo "\n";
//	echo "iTile2x2Height	=	2;";
//	echo "\n";
//	echo "\n";
//	echo "iTile2x3Width		=	2;";
//	echo "\n";
//	echo "iTile2x3Height	=	3;";
//	echo "\n";
//	echo "\n";
//	echo "iTile3x2Width		=	3;";
//	echo "\n";
//	echo "iTile3x2Height	=	2;";
//	echo "\n";
//	echo "\n";
//	echo "iTile2x4Width		=	2;";
//	echo "\n";
//	echo "iTile2x4Height	=	4;";
//	echo "\n";
//	echo "\n";
//	echo "iTile4x2Width		=	4;";
//	echo "\n";
//	echo "iTile4x2Height	=	2;";
//	echo "\n";
echo "}";
echo "\n";

$sql_command = new sql_db();
$sql_command->connect($database_host,$database_name,$database_username,$database_password);


$types = isset($_GET['t']) ? 2: 1;
$pics = isset($_GET['p']) ? $_GET['p'] : "0";

$pics = trim(preg_replace('/[^\d,]/','', urldecode(html_entity_decode(strip_tags($pics)))));
/*
if ($types===2&$pics!=0) {
$recnum = $sql_command->count_nrow("$database_gallery_mason, $database_gallery_pics","$database_gallery_mason.id","$database_gallery_mason.img_id = $database_gallery_pics.id AND $database_gallery_mason.meta_id != 10 AND $database_gallery_mason.meta_value != '320x320' AND $database_gallery_mason.img_id IN (".$pics.")");
$p=ceil($recnum/20)-1;	
}
else {*/
	$recnum = $sql_command->count_nrow("$database_gallery_mason, $database_gallery_pics","$database_gallery_mason.id","$database_gallery_mason.img_id = $database_gallery_pics.id AND $database_gallery_mason.meta_id != 10");
	$recnum = $recnum;
	$p=ceil($recnum/15)-1;
//}

echo "var main = {";
echo "\n";
echo "init: function() {";
echo "\n";
	
for($i=0;$i<=$p;$i++) {

		echo "$('#gallery".$i."').mason({";
		echo "\n";
			echo "itemSelector: '.block',";
			echo "\n";
			echo "ratio: 1,";
			echo "\n";
			echo "sizes: [";
			echo "\n";
				echo "[1,1]";
				echo "\n";
			echo "],";
			echo "\n";
			echo "columns: [";
			echo "\n";
				echo "[0, 480, 12],";
				echo "\n";
				echo "[480, 640, 4],";
				echo "\n";
				echo "[640, 960, 6],";
				echo "\n";
				echo "[960, 1080, 8],";
				echo "\n";
				echo "[1080, 1200, 8],";
				echo "\n";
				echo "[1200, 1520, 36]";
				echo "\n";
			echo "],";
			echo "\n";
			echo "promoted: [";
			echo "\n";
				echo "[iTile1x1Width, iTile1x1Height, 'tile1x1'],";
				echo "\n";
				echo "[iTile1x2Width, iTile1x2Height, 'tile1x2'],";
				echo "\n";
				echo "[iTile2x1Width, iTile2x1Height, 'tile2x1'],";
				echo "\n";
				echo "[iTile2x2Width, iTile2x2Height, 'tile2x2'],";
				echo "\n";
				echo "[iTile2x3Width, iTile2x3Height, 'tile2x3'],";
				echo "\n";
				echo "[iTile3x2Width, iTile3x2Height, 'tile3x2'],";
				echo "\n";
				echo "[iTile2x4Width, iTile2x4Height, 'tile2x4'],";
				echo "\n";
				echo "[iTile4x2Width, iTile4x2Height, 'tile4x2']";
				echo "\n";
			echo "],";
			echo "\n";
			echo "filler: {";
			echo "\n";
				echo "itemSelector: '',";
				echo "\n";
				echo "filler_class: ''";
				echo "\n";
			echo "},";
			echo "\n";
			echo "randomSizes:false,";
			echo "\n";
			echo "randomFillers:true,";
			echo "\n";
			echo "layout: 'fluid',";
			echo "\n";
			echo "gutter: 0";
			echo "\n";
	echo "}";
	echo "\n";
//	echo "function(){";
//	echo "blockHeight = window['masonBlockHeight'] - 2*masonMargin;";
//	echo "}";
	echo ");";
}
		
echo "}";
echo "\n";
echo "};";
echo "\n";
$listi .= "\n";
$listi .= "main.init();";
echo "$(document).load($(function() {";
echo $listi;
echo "\n";
echo "}));";
?>